# Generated by Django 4.2.4 on 2023-08-09 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.post')),
            ],
        ),
        migrations.CreateModel(
            name='MyReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.comment')),
            ],
        ),
    ]
