# Generated by Django 4.2.4 on 2023-08-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_community', '0002_alter_teacher_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='license',
            field=models.ImageField(upload_to='teacher_id_proofs/'),
        ),
    ]
